[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "biodivine_aeon"
repository = "https://github.com/sybila/biodivine-aeon-py/"
documentation = "https://biodivine.fi.muni.cz/docs/aeon-py/v0.1.0/"
description = "Python bindings for the tool AEON."
version = "0.2.0a5"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


